site_name: "A deep learning approach to single-trial classification for P300 spellers"

nav:
  - Introduction: introduction.md
  - Methodology: methodology.md
  - Results: results.md
  - References: references.md

plugins:
  - search
  - macros
  # - inline-svg

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

repo_url: https://github.com/weshouman/blog-p300-single-trial-classification
repo_name: weshouman/blog-p300-single-trial-classification

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-square

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js